-- @generated by subdex-codegen — DO NOT EDIT.
-- Regenerated from your schema; edit the schema and re-run codegen.

CREATE TABLE IF NOT EXISTS transfers (
    "id" TEXT PRIMARY KEY,
    "block_height" INTEGER NOT NULL,
    "from" TEXT NOT NULL,
    "to" TEXT,
    "amount" NUMERIC NOT NULL
);
CREATE INDEX IF NOT EXISTS transfers_block_height_idx ON transfers ("block_height");

