[book]
title = "subdex"
description = "A general-purpose, code-first blockchain indexer framework for Substrate chains, written in Rust."
authors = ["kunal171"]
language = "en"
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/kunal171/subdex"
edit-url-template = "https://github.com/kunal171/subdex/edit/main/docs/book/{path}"
additional-css = ["theme/custom.css"]

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
