//! End-to-end generation test: a fixture `schema.graphql` → the generated
//! `entities.rs` + migration SQL, asserting the shape of both.
//!
//! This complements the per-generator unit tests with a whole-pipeline check on
//! a realistic multi-entity schema (scalars, nullable, arrays, enum, relation,
//! and a SQL-keyword column).

const SCHEMA: &str = r#"
type Transfer @entity {
    id: ID!
    blockHeight: Int!
    from: String! @index
    to: String @index
    amount: BigInt!
    direction: Direction!
    poolIds: [String!]!
    meta: JSON
}

enum Direction { DEPOSIT WITHDRAW }

type Account @entity {
    id: ID!
    handle: String @unique
    lastTransfer: Transfer
}
"#;

#[test]
fn generates_compilable_looking_rust_and_valid_looking_sql() {
    let schema = subdex_codegen::parse_schema(SCHEMA).expect("schema parses");
    let g = subdex_codegen::generate(&schema);

    // --- entities.rs ---
    let rs = &g.entities_rs;
    assert!(rs.starts_with("// @generated by subdex-codegen"));
    assert!(rs.contains("pub struct Transfer {"));
    assert!(rs.contains("pub struct Account {"));
    assert!(rs.contains("pub enum Direction {"));
    // BigInt → decimal string, list → Vec, nullable → Option, JSON → serde_json.
    assert!(rs.contains("pub amount: String,"));
    assert!(rs.contains("pub pool_ids: Vec<String>,"));
    assert!(rs.contains("pub to: Option<String>,"));
    assert!(rs.contains("pub meta: Option<serde_json::Value>,"));
    // Enum round-trip.
    assert!(rs.contains("Self::Deposit => \"DEPOSIT\","));

    // --- upsert helpers (same file as the structs) ---
    assert!(rs.contains("impl Transfer {"));
    assert!(rs.contains("pub async fn upsert<'e, E>"));
    assert!(rs.contains("E: sqlx::PgExecutor<'e>"));
    // Upsert on the PK; BigInt binds via ::text::numeric; keyword column quoted.
    assert!(rs.contains("ON CONFLICT (\"id\") DO UPDATE SET"));
    assert!(rs.contains("$5::text::numeric") || rs.contains("::text::numeric"));
    assert!(rs.contains(".bind(&self.from)"));
    // The SQL must be a raw literal — it contains double-quoted identifiers, so a
    // plain "…" literal would not compile.
    assert!(rs.contains("r#\"INSERT INTO transfers"));

    // --- migration ---
    let sql = &g.migration_sql;
    assert_eq!(g.migration_name, "0001_schema.sql");
    assert!(sql.contains("CREATE TABLE IF NOT EXISTS transfers ("));
    assert!(sql.contains("CREATE TABLE IF NOT EXISTS accounts ("));
    // Keyword columns quoted (from/to), array + jsonb, PK, unique, index.
    assert!(sql.contains("\"from\" TEXT NOT NULL"));
    assert!(sql.contains("\"pool_ids\" TEXT[] NOT NULL"));
    assert!(sql.contains("\"meta\" JSONB"));
    assert!(sql.contains("\"id\" TEXT PRIMARY KEY"));
    assert!(sql.contains("\"handle\" TEXT UNIQUE"));
    assert!(sql.contains("CREATE INDEX IF NOT EXISTS transfers_from_idx ON transfers (\"from\")"));

    // --- graphql.rs ---
    let gql = &g.graphql_rs;
    assert!(gql.starts_with("// @generated by subdex-codegen"));
    assert!(gql.contains("#[derive(SimpleObject, Debug, Clone)]"));
    assert!(gql.contains("pub struct Transfer {"));
    assert!(gql.contains("async fn transfers("));
    assert!(gql.contains("async fn transfers_count("));
    // BigInt / JSON read as text; keyword column quoted in the select.
    assert!(gql.contains("\"amount\"::text AS \"amount\""));
    assert!(gql.contains("\"meta\"::text AS \"meta\""));
    assert!(gql.contains(".clamp(1, 200)"));
    // Root merges every entity query + the framework status query.
    assert!(gql.contains("pub struct QueryRoot(TransferQuery, AccountQuery, StatusQuery);"));

    // Deterministic: regenerating the same schema is byte-identical.
    let g2 = subdex_codegen::generate(&schema);
    assert_eq!(g.entities_rs, g2.entities_rs);
    assert_eq!(g.migration_sql, g2.migration_sql);
    assert_eq!(g.graphql_rs, g2.graphql_rs);
}

#[test]
fn generates_the_whole_real_production_schema_without_error() {
    // The parser already handles the real 103-entity unit-indexer schema; make
    // sure the *generators* do too (no panics, non-trivial output). This path is
    // skipped unless the sibling checkout is present.
    let dir = std::path::Path::new("../../../unit-indexer/schema");
    if !dir.is_dir() {
        eprintln!("skipping: {} not present", dir.display());
        return;
    }
    let schema = subdex_codegen::parse_schema_dir(dir).expect("real schema parses");
    let g = subdex_codegen::generate(&schema);
    assert!(schema.entities.len() > 50, "expected many entities");
    assert!(g.entities_rs.contains("pub struct "));
    assert!(g.migration_sql.contains("CREATE TABLE IF NOT EXISTS "));
}
