//! Generate Rust entity structs from the [`Schema`] model.
//!
//! One `struct` per `@entity`, fields typed by the fixed scalar mapping (see
//! [`crate::model::Scalar`]). Enums become plain Rust `enum`s with a
//! string round-trip, since the DB stores them as `TEXT`.
//!
//! The output is a single `entities.rs` a builder commits and imports. It derives
//! `Debug` + `Clone` and nothing DB-specific — the *upsert* helpers (a later PR)
//! add the persistence, keeping this file a plain data model.

use crate::model::{Entity, EnumDef, FieldType, Schema};

/// The header stamped on every generated file.
pub const GENERATED_HEADER: &str = "\
// @generated by subdex-codegen — DO NOT EDIT.
//
// This file is regenerated from your schema. Edit the schema and re-run
// `subdex-codegen generate` instead of changing anything here.
";

/// Render the whole `entities.rs` for a schema.
pub fn render(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("#![allow(dead_code)]\n\n");

    // `serde_json::Value` is only referenced if some field is JSON — but importing
    // it unconditionally would warn when unused, so we qualify at the use site
    // (`serde_json::Value`) and require the crate to depend on serde_json only when
    // it actually has a JSON field. We note that in the module doc.
    if schema.entities.iter().any(has_json_field) {
        out.push_str("// Note: JSON fields require a `serde_json` dependency.\n\n");
    }

    for e in &schema.enums {
        out.push_str(&render_enum(e));
        out.push('\n');
    }
    for e in &schema.entities {
        out.push_str(&render_entity(e));
        out.push('\n');
    }
    out
}

fn has_json_field(e: &Entity) -> bool {
    e.fields.iter().any(|f| {
        matches!(
            &f.ty,
            FieldType::Scalar(crate::model::Scalar::Json)
                | FieldType::ScalarList(crate::model::Scalar::Json)
        )
    })
}

fn render_entity(e: &Entity) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "/// `{}` — maps to the `{}` table.\n",
        e.name, e.table
    ));
    s.push_str("#[derive(Debug, Clone)]\n");
    s.push_str(&format!("pub struct {} {{\n", e.name));
    for f in &e.fields {
        // Keep the original GraphQL field name as the Rust field name, converted
        // to snake_case (Rust convention) — this is the `column`, which is already
        // snake_case of the field.
        let doc = match &f.ty {
            FieldType::Relation(target) => {
                format!("    /// References `{target}.id`.\n")
            }
            FieldType::Enum(en) => format!("    /// One of the `{en}` enum values.\n"),
            _ => String::new(),
        };
        s.push_str(&doc);
        s.push_str(&format!("    pub {}: {},\n", f.column, f.rust_type()));
    }
    s.push_str("}\n");
    s
}

fn render_enum(e: &EnumDef) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "/// The `{}` enum (stored as its variant name in a `TEXT` column).\n",
        e.name
    ));
    s.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    s.push_str(&format!("pub enum {} {{\n", e.name));
    for v in &e.values {
        s.push_str(&format!("    {},\n", pascal_variant(v)));
    }
    s.push_str("}\n\n");

    // as_str / from_str for the TEXT round-trip.
    s.push_str(&format!("impl {} {{\n", e.name));
    s.push_str("    /// The value as stored in the database.\n");
    s.push_str("    pub fn as_str(&self) -> &'static str {\n");
    s.push_str("        match self {\n");
    for v in &e.values {
        s.push_str(&format!(
            "            Self::{} => \"{}\",\n",
            pascal_variant(v),
            v
        ));
    }
    s.push_str("        }\n    }\n\n");
    s.push_str("    /// Parse a stored value back into the enum.\n");
    s.push_str("    pub fn from_str(s: &str) -> Option<Self> {\n");
    s.push_str("        Some(match s {\n");
    for v in &e.values {
        s.push_str(&format!(
            "            \"{}\" => Self::{},\n",
            v,
            pascal_variant(v)
        ));
    }
    s.push_str("            _ => return None,\n");
    s.push_str("        })\n    }\n}\n");
    s
}

/// Turn a GraphQL enum value (`SCREAMING_SNAKE` or `PascalCase`) into a Rust
/// PascalCase variant: `DEPOSIT` → `Deposit`, `IN_PROGRESS` → `InProgress`.
fn pascal_variant(value: &str) -> String {
    value
        .split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(first) => {
                    first.to_ascii_uppercase().to_string() + &c.as_str().to_ascii_lowercase()
                }
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::parse_schema;

    fn gen(src: &str) -> String {
        render(&parse_schema(src).unwrap())
    }

    #[test]
    fn struct_has_a_field_per_column_with_the_right_types() {
        let out = gen(
            "type Transfer @entity { id: ID! amount: BigInt! blockHeight: Int! note: String tags: [String!]! }",
        );
        assert!(out.contains("pub struct Transfer {"));
        assert!(out.contains("pub id: String,"));
        // BigInt is a decimal string.
        assert!(out.contains("pub amount: String,"));
        assert!(out.contains("pub block_height: i32,"));
        // Nullable → Option.
        assert!(out.contains("pub note: Option<String>,"));
        // Scalar list → Vec.
        assert!(out.contains("pub tags: Vec<String>,"));
        // The DO-NOT-EDIT header is present.
        assert!(out.contains("DO NOT EDIT"));
    }

    #[test]
    fn enum_gets_variants_and_str_roundtrip() {
        let out = gen("type T @entity { id: ID! s: Status! } enum Status { IN_PROGRESS DONE }");
        assert!(out.contains("pub enum Status {"));
        // SCREAMING_SNAKE → PascalCase variant.
        assert!(out.contains("    InProgress,"));
        assert!(out.contains("    Done,"));
        // Round-trip keeps the original stored string.
        assert!(out.contains("Self::InProgress => \"IN_PROGRESS\","));
        assert!(out.contains("\"DONE\" => Self::Done,"));
        // The field itself is a String (enums are TEXT in v1).
        assert!(out.contains("pub s: String,"));
    }

    #[test]
    fn relation_field_is_a_string_id_with_a_doc() {
        let out = gen("type A @entity { id: ID! owner: B! } type B @entity { id: ID! }");
        assert!(out.contains("References `B.id`."));
        assert!(out.contains("pub owner: String,"));
    }

    #[test]
    fn json_field_triggers_the_serde_note() {
        let out = gen("type T @entity { id: ID! meta: JSON }");
        assert!(out.contains("serde_json"));
        assert!(out.contains("pub meta: Option<serde_json::Value>,"));
    }

    #[test]
    fn pascal_variant_cases() {
        assert_eq!(pascal_variant("DEPOSIT"), "Deposit");
        assert_eq!(pascal_variant("IN_PROGRESS"), "InProgress");
        assert_eq!(pascal_variant("Done"), "Done");
    }
}
