//! Generate a SQL migration from the [`Schema`] model.
//!
//! One `CREATE TABLE IF NOT EXISTS` per `@entity`:
//! - `id` → `TEXT PRIMARY KEY`,
//! - `@unique` → `UNIQUE`, non-null fields → `NOT NULL`,
//! - scalar lists → Postgres arrays (`TEXT[]`, …),
//! - `@index` → a `CREATE INDEX IF NOT EXISTS` after the table.
//!
//! The whole file is idempotent (`IF NOT EXISTS` throughout), so it runs cleanly
//! through the framework's per-handler migration machinery
//! (`PgStore::run_handler_migrations`, see #33) on a fresh *or* existing database.

use crate::model::{Entity, Field, Schema};

/// Render the migration SQL for a schema. Deterministic (stable field order),
/// so regenerating an unchanged schema produces byte-identical output.
pub fn render(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("-- @generated by subdex-codegen — DO NOT EDIT.\n");
    out.push_str("-- Regenerated from your schema; edit the schema and re-run codegen.\n\n");

    for e in &schema.entities {
        out.push_str(&render_table(e));
        out.push('\n');
    }
    out
}

fn render_table(e: &Entity) -> String {
    let mut s = String::new();
    s.push_str(&format!("CREATE TABLE IF NOT EXISTS {} (\n", e.table));

    let col_lines: Vec<String> = e.fields.iter().map(column_def).collect();
    s.push_str(&col_lines.join(",\n"));
    s.push_str("\n);\n");

    // Indexes for @index fields (the PK and UNIQUE columns are already indexed by
    // Postgres, so only add explicit non-unique indexes here). The index *name*
    // uses the bare column; the column *reference* is quoted (it may be a keyword
    // like `from`/`to`, which real transfer schemas use).
    for f in &e.fields {
        if f.indexed && !f.is_id && !f.unique {
            s.push_str(&format!(
                "CREATE INDEX IF NOT EXISTS {table}_{col}_idx ON {table} ({colq});\n",
                table = e.table,
                col = f.column,
                colq = quote_ident(&f.column),
            ));
        }
    }
    s
}

/// Quote a column identifier so SQL keywords (`from`, `to`, `order`, …) — common
/// in real schemas — are valid. Always quoting is safe and unambiguous.
fn quote_ident(col: &str) -> String {
    format!("\"{}\"", col.replace('"', "\"\""))
}

/// One column definition line (leading indentation included).
fn column_def(f: &Field) -> String {
    let mut parts = vec![format!("    {} {}", quote_ident(&f.column), f.pg_type())];
    if f.is_id {
        parts.push("PRIMARY KEY".to_string());
    } else {
        if !f.nullable {
            parts.push("NOT NULL".to_string());
        }
        if f.unique {
            parts.push("UNIQUE".to_string());
        }
    }
    parts.join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::parse_schema;

    fn gen(src: &str) -> String {
        render(&parse_schema(src).unwrap())
    }

    #[test]
    fn creates_a_table_with_pk_notnull_and_types() {
        let sql =
            gen("type Transfer @entity { id: ID! amount: BigInt! note: String blockHeight: Int! }");
        assert!(sql.contains("CREATE TABLE IF NOT EXISTS transfers ("));
        assert!(sql.contains("\"id\" TEXT PRIMARY KEY"));
        assert!(sql.contains("\"amount\" NUMERIC NOT NULL"));
        // Nullable → no NOT NULL.
        assert!(sql.contains("\"note\" TEXT"));
        assert!(!sql.contains("\"note\" TEXT NOT NULL"));
        assert!(sql.contains("\"block_height\" INTEGER NOT NULL"));
        assert!(sql.contains("DO NOT EDIT"));
    }

    #[test]
    fn unique_and_index_are_emitted() {
        let sql =
            gen("type Account @entity { id: ID! handle: String @unique from: String! @index }");
        // UNIQUE inline on the column.
        assert!(sql.contains("\"handle\" TEXT UNIQUE"));
        // @index → a separate CREATE INDEX; the keyword column `from` is quoted.
        assert!(
            sql.contains("CREATE INDEX IF NOT EXISTS accounts_from_idx ON accounts (\"from\")"),
            "got:\n{sql}"
        );
        // A UNIQUE column is already indexed → no explicit index for it.
        assert!(!sql.contains("accounts_handle_idx"));
    }

    #[test]
    fn keyword_columns_are_quoted() {
        // `from`/`to`/`order` are SQL keywords — real transfer schemas use them.
        let sql = gen("type Transfer @entity { id: ID! from: String! to: String! }");
        assert!(sql.contains("\"from\" TEXT NOT NULL"));
        assert!(sql.contains("\"to\" TEXT NOT NULL"));
    }

    #[test]
    fn scalar_lists_are_postgres_arrays() {
        let sql = gen("type Swap @entity { id: ID! poolIds: [String!]! counts: [Int!] }");
        assert!(sql.contains("\"pool_ids\" TEXT[] NOT NULL"));
        assert!(sql.contains("\"counts\" INTEGER[]"));
    }

    #[test]
    fn enum_and_relation_columns_are_text() {
        let sql = gen(
            "type A @entity { id: ID! s: Status! owner: B! } type B @entity { id: ID! } enum Status { X Y }",
        );
        assert!(sql.contains("\"s\" TEXT NOT NULL"));
        assert!(sql.contains("\"owner\" TEXT NOT NULL"));
    }

    #[test]
    fn output_is_idempotent_across_calls() {
        let src = "type T @entity { id: ID! a: String @index }";
        assert_eq!(gen(src), gen(src), "deterministic output");
        // Everything uses IF NOT EXISTS so it's safe to re-apply.
        assert!(gen(src).contains("CREATE TABLE IF NOT EXISTS"));
        assert!(gen(src).contains("CREATE INDEX IF NOT EXISTS"));
    }
}
