//! Generate an async-graphql read API from the [`Schema`] model.
//!
//! For each `@entity` this emits, into a `graphql.rs` a builder commits:
//! - a `#[derive(async_graphql::SimpleObject)]` **read model** (a row of the
//!   table, exposed as a GraphQL type), and
//! - an `#[Object] impl <Entity>Query` with two resolvers: a **list** query
//!   (`limit`-clamped, ordered by `id`, with an optional `id` equality filter)
//!   and a **count** query.
//!
//! Then one `#[derive(MergedObject)] QueryRoot` flattens every entity's query
//! plus the framework's built-in `StatusQuery` (`indexerStatus`) into a single
//! GraphQL Query — exactly the hand-written shape in `examples/transfers`.
//!
//! ## Deliberate scope (v1)
//! - Read-only: a list + a count per entity; no mutations, no relation joins
//!   (relations are id strings), no cursor pagination.
//! - SQL is **parameterized** — the `limit`, the optional `id` filter, and the
//!   ordering column are never string-interpolated from user input.
//! - Field names become camelCase automatically (async-graphql's default rename),
//!   so a snake_case Rust field `block_height` serves as `blockHeight`.
//!
//! ## What the generated code depends on
//! `async-graphql` and `sqlx` (postgres) in the builder's crate, plus
//! `subdex-graphql` for `StatusQuery`. The read model is separate from the
//! `entities.rs` structs on purpose: the persistence model and the API model
//! have different derives and can diverge later without coupling.

use crate::model::{Entity, FieldType, Scalar, Schema};

/// The header stamped on the generated `graphql.rs`.
pub const GENERATED_HEADER: &str = "\
// @generated by subdex-codegen — DO NOT EDIT.
//
// Regenerated from your schema. Edit the schema and re-run `subdex-codegen
// generate` instead of changing anything here.
";

/// Render the whole `graphql.rs` for a schema.
pub fn render(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("#![allow(dead_code)]\n\n");
    out.push_str(
        "use async_graphql::{Context, MergedObject, Object, SimpleObject};\n\
         use sqlx::{PgPool, Row};\n\
         use subdex_graphql::StatusQuery;\n\n",
    );

    for e in &schema.entities {
        out.push_str(&render_read_model(e));
        out.push('\n');
        out.push_str(&render_query(e));
        out.push('\n');
    }

    out.push_str(&render_root(schema));
    out
}

/// The GraphQL type for a field: the same scalars as the Rust model, except JSON
/// is surfaced as a `String` (read from JSONB as text) to avoid a custom scalar.
fn gql_type(f: &crate::model::Field) -> String {
    let base = match &f.ty {
        FieldType::Scalar(Scalar::Json) => "String".to_string(),
        FieldType::Scalar(s) => s.rust_type().to_string(),
        FieldType::ScalarList(Scalar::Json) => "Vec<String>".to_string(),
        FieldType::ScalarList(s) => format!("Vec<{}>", s.rust_type()),
        FieldType::Enum(_) | FieldType::Relation(_) => "String".to_string(),
    };
    if f.nullable {
        format!("Option<{base}>")
    } else {
        base
    }
}

/// The `SELECT`-list expression for a column: JSON/BigInt read as text so they
/// map to the `String` GraphQL type; everything else selected directly.
fn select_expr(f: &crate::model::Field) -> String {
    let col = quote_ident(&f.column);
    match &f.ty {
        // NUMERIC and JSONB don't map to a Rust String on their own — cast to text.
        FieldType::Scalar(Scalar::BigInt) | FieldType::Scalar(Scalar::Json) => {
            format!("{col}::text AS {col}")
        }
        _ => col,
    }
}

fn render_read_model(e: &Entity) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "/// A row of the `{}` table, exposed as a GraphQL type.\n",
        e.table
    ));
    s.push_str("#[derive(SimpleObject, Debug, Clone)]\n");
    s.push_str(&format!("pub struct {} {{\n", e.name));
    for f in &e.fields {
        s.push_str(&format!("    pub {}: {},\n", f.column, gql_type(f)));
    }
    s.push_str("}\n");
    s
}

fn render_query(e: &Entity) -> String {
    let table = &e.table;
    let id_col = e
        .id_field()
        .map(|f| quote_ident(&f.column))
        .unwrap_or_else(|| "\"id\"".to_string());
    let select_list = e
        .fields
        .iter()
        .map(select_expr)
        .collect::<Vec<_>>()
        .join(", ");
    let row_binds = e
        .fields
        .iter()
        .map(|f| format!("                {}: r.get(\"{}\"),", f.column, f.column))
        .collect::<Vec<_>>()
        .join("\n");

    let mut s = String::new();
    s.push_str(&format!(
        "/// Query resolvers for the `{}` table.\n#[derive(Default)]\npub struct {}Query;\n\n",
        e.table, e.name
    ));
    s.push_str(&format!("#[Object]\nimpl {}Query {{\n", e.name));

    // --- list resolver ---
    s.push_str(&format!(
        "    /// List `{table}` rows, newest `id` first. `limit` is clamped to\n\
         \x20   /// `[1, 200]` (default 25); `id` optionally filters to one row.\n"
    ));
    s.push_str(&format!(
        "    async fn {snake}(\n\
         \x20       &self,\n\
         \x20       ctx: &Context<'_>,\n\
         \x20       limit: Option<i32>,\n\
         \x20       id: Option<String>,\n\
         \x20   ) -> async_graphql::Result<Vec<{name}>> {{\n",
        snake = crate::model::to_snake_case(&e.name) + "s",
        name = e.name,
    ));
    s.push_str("        let pool = ctx.data::<PgPool>()?;\n");
    s.push_str("        let limit = limit.unwrap_or(25).clamp(1, 200) as i64;\n");
    // Two static, parameterized queries (with/without the id filter). The SQL is
    // emitted as a *raw* Rust literal (`r#"…"#`) because the select list contains
    // double-quoted identifiers (`"from"`, `"id"`) — a plain "…" literal would be
    // terminated by the first embedded quote and would not compile.
    let sql_filtered = format!(
        "SELECT {select_list} FROM {table} WHERE {id_col} = $1 ORDER BY {id_col} DESC LIMIT $2"
    );
    let sql_all = format!("SELECT {select_list} FROM {table} ORDER BY {id_col} DESC LIMIT $1");
    s.push_str(&format!(
        "        let rows = match id {{\n\
         \x20           Some(id) => {{\n\
         \x20               sqlx::query(r#\"{sql_filtered}\"#)\n\
         \x20                   .bind(id)\n\
         \x20                   .bind(limit)\n\
         \x20                   .fetch_all(pool)\n\
         \x20                   .await?\n\
         \x20           }}\n\
         \x20           None => {{\n\
         \x20               sqlx::query(r#\"{sql_all}\"#)\n\
         \x20                   .bind(limit)\n\
         \x20                   .fetch_all(pool)\n\
         \x20                   .await?\n\
         \x20           }}\n\
         \x20       }};\n"
    ));
    s.push_str("        Ok(rows\n            .into_iter()\n");
    s.push_str(&format!(
        "            .map(|r| {name} {{\n{row_binds}\n            }})\n",
        name = e.name,
    ));
    s.push_str("            .collect())\n");
    s.push_str("    }\n\n");

    // --- count resolver ---
    s.push_str(&format!(
        "    /// Total number of `{table}` rows.\n\
         \x20   async fn {snake}_count(&self, ctx: &Context<'_>) -> async_graphql::Result<i64> {{\n\
         \x20       let pool = ctx.data::<PgPool>()?;\n\
         \x20       let row = sqlx::query(\"SELECT count(*) AS n FROM {table}\").fetch_one(pool).await?;\n\
         \x20       Ok(row.get(\"n\"))\n\
         \x20   }}\n",
        snake = crate::model::to_snake_case(&e.name) + "s",
    ));
    s.push_str("}\n");
    s
}

fn render_root(schema: &Schema) -> String {
    // MergedObject flattens every entity query plus the framework StatusQuery
    // into one GraphQL Query type.
    let members = schema
        .entities
        .iter()
        .map(|e| format!("{}Query", e.name))
        .chain(std::iter::once("StatusQuery".to_string()))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "/// The combined GraphQL query root: every entity's queries plus the\n\
         /// framework's built-in `indexerStatus`.\n\
         #[derive(MergedObject, Default)]\n\
         pub struct QueryRoot({members});\n"
    )
}

/// Quote a SQL identifier so keyword columns (`from`, `to`, …) stay valid —
/// the same rule the migration + upsert generators use.
fn quote_ident(col: &str) -> String {
    format!("\"{}\"", col.replace('"', "\"\""))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::parse_schema;

    fn gen(src: &str) -> String {
        render(&parse_schema(src).unwrap())
    }

    #[test]
    fn read_model_and_resolvers_are_generated() {
        let out = gen(
            "type Transfer @entity { id: ID! amount: BigInt! from: String! @index count: Int }",
        );
        // Read model.
        assert!(out.contains("#[derive(SimpleObject, Debug, Clone)]"));
        assert!(out.contains("pub struct Transfer {"));
        assert!(out.contains("pub amount: String,")); // BigInt -> decimal String
        assert!(out.contains("pub count: Option<i32>,")); // nullable Int
                                                          // List + count resolvers.
        assert!(out.contains("pub struct TransferQuery;"));
        assert!(out.contains("async fn transfers("));
        assert!(out.contains("async fn transfers_count("));
        // limit clamp + parameterized query.
        assert!(out.contains(".clamp(1, 200)"));
        assert!(out.contains("ORDER BY \"id\" DESC LIMIT $1"));
        // The SQL must be a raw literal — it embeds double-quoted identifiers, so a
        // plain "…" literal would not compile. (Same bug class as the upsert gen.)
        assert!(
            out.contains("sqlx::query(r#\"SELECT"),
            "query SQL must be a raw string literal, got:\n{out}"
        );
    }

    #[test]
    fn bigint_and_json_are_selected_as_text() {
        let out = gen("type T @entity { id: ID! amount: BigInt! meta: JSON }");
        // NUMERIC / JSONB read as text so they map to a String GraphQL field.
        assert!(out.contains("\"amount\"::text AS \"amount\""));
        assert!(out.contains("\"meta\"::text AS \"meta\""));
        assert!(out.contains("pub meta: Option<String>,"));
    }

    #[test]
    fn keyword_column_is_quoted_in_select() {
        let out = gen("type Transfer @entity { id: ID! from: String! }");
        assert!(out.contains("\"from\""));
        // never an unquoted bare `from ` in the select list
        assert!(!out.contains("SELECT \"id\", from FROM"));
    }

    #[test]
    fn root_merges_all_entities_plus_status() {
        let out = gen("type A @entity { id: ID! } type B @entity { id: ID! }");
        assert!(out.contains("#[derive(MergedObject, Default)]"));
        assert!(out.contains("pub struct QueryRoot(AQuery, BQuery, StatusQuery);"));
    }
}
